//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleLinkedList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoubleLinkedList.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olivia,F,18451
        ///Emma,F,17102
        ///Ava,F,14440
        ///Sophia,F,13714
        ///Isabella,F,13306
        ///Charlotte,F,13138
        ///Amelia,F,12862
        ///Mia,F,12414
        ///Harper,F,10442
        ///Evelyn,F,10392
        ///Abigail,F,9106
        ///Emily,F,8213
        ///Ella,F,8079
        ///Elizabeth,F,7844
        ///Camila,F,7809
        ///Luna,F,7755
        ///Sofia,F,7355
        ///Avery,F,7311
        ///Mila,F,7309
        ///Aria,F,7072
        ///Scarlett,F,7044
        ///Penelope,F,6697
        ///Layla,F,6478
        ///Chloe,F,6361
        ///Victoria,F,6344
        ///Madison,F,6269
        ///Eleanor,F,6164
        ///Grace,F,6062
        ///Nora,F,5899
        ///Riley,F,5676
        ///Zoey,F,5650
        ///Hannah,F,5586
        ///Hazel,F,5431
        ///Lily,F,5419
        ///Ellie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yob2019 {
            get {
                return ResourceManager.GetString("yob2019", resourceCulture);
            }
        }
    }
}
